// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynwwmjroallnedgtmgcw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlud3dtanJvYWxsbmVkZ3RtZ2N3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxOTg2MDIsImV4cCI6MjA2MDc3NDYwMn0.DHWW_7a45lp5wzEI12Xy52IQ5HHzsnukGJlqHUGod1o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);